#DATABASE
spring :
  datasource :
    driver-class-name : ${DB_DRIVER}
    url : ${DB_URL}
    username : ${DB_USER}
    password : ${DB_PASSWORD}

  #JPA SQL
  jpa :
    show-sql : ${JPA_HIBERNATE_SHOW_SQL}
    properties :
      hibernate :
        format_sql : ${JPA_HIBERNATE_FORMAT_SQL}
        ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
        dialect : ${JPA_HIBERNATE_DIALECT}