#DATABASE
spring :
  datasource :
    driver-class-name :
    url :
    username :
    password :

  #JPA SQL
  jpa:
    show-sql:
    properties:
      hibernate:
        format_sql:
        ddl-auto:
        dialect: